# SPDX-FileCopyrightText: NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0

version: "3"
services:
  node:
    build:
     context: .
     dockerfile: infrastructure/docker/dockerfile-node
    volumes:
       - ./:/code
    working_dir: /code
    command: sh -c "test -d node_modules || npm install; npm run dev"
    environment:
      HOST: 0.0.0.0
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CALLBACK: ${KEYCLOAK_CALLBACK}
      KEYCLOAK_AUTHORIZATION_URI: ${KEYCLOAK_AUTHORIZATION_URI}
      KEYCLOAK_USERINFO_URI: ${KEYCLOAK_USERINFO_URI}
      KEYCLOAK_ACCOUNT_URI: ${KEYCLOAK_ACCOUNT_URI}
      API: ${API}
    ports:
      - "${SERVER_PORT:-3000}:3000"
