export default {
  IT: 'Italy',
  ITC: 'Italy Nord-ovest',
  ITD: 'Italy Nord-est',
  ITE: 'Italy Centro (I)',
  ITF: 'Italy Sud',
  ITG: 'Italy Isole',
  ITC1: 'Piemonte',
  ITC2: "Valle d'Aosta / Vallée d'Aoste",
  ITC3: 'Liguria',
  ITC4: 'Lombardia',
  ITDA: 'Trentino Alto Adige / Südtirol',
  ITD1: 'Provincia Autonoma Bolzano / Bozen',
  ITD2: 'Provincia Autonoma Trento',
  ITD3: 'Veneto',
  ITD4: 'Friuli-Venezia Giulia',
  ITD5: 'Emilia-Romagna',
  ITE1: 'Toscana',
  ITE2: 'Umbria',
  ITE3: 'Marche',
  ITE4: 'Lazio',
  ITF1: 'Abruzzo',
  ITF2: 'Molise',
  ITF3: 'Campania',
  ITF4: 'Puglia',
  ITF5: 'Basilicata',
  ITF6: 'Calabria',
  ITG1: 'Sicilia',
  ITG2: 'Sardegna'
}
