name: ci davinci-innovation-scoreboard-web

on:
  push:
    branches: [ master, development ]
    paths:
      - "!README.md"
  pull_request:
    branches: [ master, development ]
    paths:
      - "!README.md"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run test # will run `yarn run test` command
