name: CI/CD

on: push

env:
  AWS_REGION : "eu-west-1"
  NODE_VERSION: 16.x

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Test code
        uses: noi-techpark/github-actions/node-test@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/development'
    needs: test
    concurrency: deploy-test
    env:
      AWS_S3_BUCKET_NAME : "test-innovation-web"
      API: "https://api.innovation.davinci.testingmachine.eu/v1/"
      KEYCLOAK_CLIENT_ID: "davinci-innovation-scoreboard-web"
      KEYCLOAK_CALLBACK: "https://innovation.davinci.testingmachine.eu/callback"
      KEYCLOAK_AUTHORIZATION_URI: "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/auth"
      KEYCLOAK_USERINFO_URI: "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/userinfo"
      KEYCLOAK_ACCOUNT_URI: "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/account"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build code
        uses: noi-techpark/github-actions/node-build@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          build-command: 'npm run generate'
      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v1
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist

  deploy-prod:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    needs: test
    concurrency: deploy-prod
    env:
      AWS_S3_BUCKET_NAME : "prod-innovation-web"
      API: "https://api.innovation.davinci.bz.it/v1/"
      KEYCLOAK_CLIENT_ID: "davinci-innovation-scoreboard-web"
      KEYCLOAK_CALLBACK: "https://innovation.davinci.bz.it/callback"
      KEYCLOAK_AUTHORIZATION_URI: "https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/auth"
      KEYCLOAK_USERINFO_URI: "https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/userinfo"
      KEYCLOAK_ACCOUNT_URI: "https://auth.opendatahub.bz.it/auth/realms/noi/account"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build code
        uses: noi-techpark/github-actions/node-build@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          build-command: 'npm run generate'
      - name: Sync to S3 bucket
        uses: noi-techpark/github-actions/aws-s3-bucket-sync@v1
        with:
          access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          region: ${{ env.AWS_REGION }}
          s3-bucket-name: ${{ env.AWS_S3_BUCKET_NAME }}
          folder: ./dist
