name: CI/CD

on: push

env:
  AWS_REGION : "eu-west-1"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run test

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/development'
    needs: test
    env:
      BUCKET_NAME : "test-innovation-web"
      API: "https://api.innovation.davinci.testingmachine.eu/v1/"
      KEYCLOAK_CLIENT_ID: "davinci-innovation-scoreboard-web"
      KEYCLOAK_CALLBACK: "https://innovation.davinci.testingmachine.eu/callback"
      KEYCLOAK_AUTHORIZATION_URI: "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/auth"
      KEYCLOAK_USERINFO_URI: "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/protocol/openid-connect/userinfo"
      KEYCLOAK_ACCOUNT_URI: "https://auth.opendatahub.testingmachine.eu/auth/realms/noi/account"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run generate
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 sync --delete ./dist s3://${{ env.BUCKET_NAME }}

  deploy-prod:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    needs: test
    env:
      BUCKET_NAME : "prod-innovation-web"
      API: "https://api.innovation.davinci.bz.it/v1/"
      KEYCLOAK_CLIENT_ID: "davinci-innovation-scoreboard-web"
      KEYCLOAK_CALLBACK: "https://innovation.davinci.bz.it/callback"
      KEYCLOAK_AUTHORIZATION_URI: "https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/auth"
      KEYCLOAK_USERINFO_URI: "https://auth.opendatahub.bz.it/auth/realms/noi/protocol/openid-connect/userinfo"
      KEYCLOAK_ACCOUNT_URI: "https://auth.opendatahub.bz.it/auth/realms/noi/account"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run generate
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 sync --delete ./dist s3://${{ env.BUCKET_NAME }}
