name: CI

on: push

env:
  AWS_REGION : "eu-west-1"
  TEST_BUCKET_NAME : "test-innovation-web"
  PROD_BUCKET_NAME : "prod-innovation-web"

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run test

  deploy-test:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/development'
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run generate
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 sync ./dist s3://${{ env.TEST_BUCKET_NAME }}

  deploy-prod:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/master'
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm ci
      - run: npm run generate
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: aws s3 sync ./dist s3://${{ env.PROD_BUCKET_NAME }}
